"""message

Revision ID: 1128278c8863
Revises: 49031cad686b
Create Date: 2026-05-06 16:42:05.547849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1128278c8863'
down_revision = '49031cad686b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_pending_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('backup_codes', sa.JSON(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phonenumber', sa.String(length=200), nullable=False))
        batch_op.create_unique_constraint(None, ['phonenumber'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phonenumber')

    with op.batch_alter_table('security_settings', schema=None) as batch_op:
        batch_op.drop_column('backup_codes')
        batch_op.drop_column('totp_pending_secret')

    # ### end Alembic commands ###
