"""your message

Revision ID: 3fe9b4e011a5
Revises: 5d9e14ebe5b8
Create Date: 2026-06-04 14:13:08.470761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe9b4e011a5'
down_revision = '5d9e14ebe5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_card', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cardnumber', sa.String(length=19), nullable=True))
        batch_op.add_column(sa.Column('securitycode', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accountnumber', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['cardnumber'])
        batch_op.drop_constraint(batch_op.f('cards_account_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('cards_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'accounts', ['account_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('is_default')
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cards_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('cards_account_id_fkey'), 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('accountnumber')
        batch_op.drop_column('securitycode')
        batch_op.drop_column('cardnumber')
        batch_op.drop_column('is_card')

    # ### end Alembic commands ###
