"""message

Revision ID: 49031cad686b
Revises: 8b593714a49a
Create Date: 2026-04-27 13:30:20.887492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49031cad686b'
down_revision = '8b593714a49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_settings', schema=None) as batch_op:
        batch_op.alter_column('verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('security_settings', schema=None) as batch_op:
        batch_op.alter_column('verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
