"""message

Revision ID: 5f6e4264732d
Revises: 1128278c8863
Create Date: 2026-05-06 16:44:52.523742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6e4264732d'
down_revision = '1128278c8863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_pending_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('backup_codes', sa.JSON(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phonenumber', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phonenumber')

    with op.batch_alter_table('security_settings', schema=None) as batch_op:
        batch_op.drop_column('backup_codes')
        batch_op.drop_column('totp_pending_secret')

    # ### end Alembic commands ###
