"""message

Revision ID: 7855e6de6a32
Revises: 5f6e4264732d
Create Date: 2026-05-06 22:48:38.935681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7855e6de6a32'
down_revision = '5f6e4264732d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last4', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_primary', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('is_primary')
        batch_op.drop_column('balance')
        batch_op.drop_column('last4')
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
