"""message

Revision ID: 97562f34e652
Revises: 9b862ba48b18
Create Date: 2026-05-07 18:38:42.588111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97562f34e652'
down_revision = '9b862ba48b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('cardnumber', sa.String(length=12), nullable=True),
    sa.Column('securitycode', sa.Integer(), nullable=True),
    sa.Column('last4', sa.String(length=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('active')

    op.drop_table('cards')
    # ### end Alembic commands ###
