"""message

Revision ID: ae8143ff0ee1
Revises: 2729f3b1d0e8
Create Date: 2026-05-12 11:04:09.066782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8143ff0ee1'
down_revision = '2729f3b1d0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faq_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faq_items_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faq_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faq_items_category'))

    op.drop_table('faq_items')
    # ### end Alembic commands ###
